# Generated by Django 5.1.6 on 2025-05-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvadd',
            name='age',
            field=models.DateField(blank=True, null=True),
        ),
    ]
