# Generated by Django 5.1.6 on 2025-05-03 06:23

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0003_alter_cvadd_cv_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvadd',
            name='cv_file',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='cv_adds/'),
        ),
    ]
